-- WolfOrder: تحسينات الأداء + طلبات إنستغرام + المخزون الآمن
-- Migration إضافية وغير مدمّرة: لا تحذف أي جدول أو سجل طلبات.
-- نفّذ الملف مرة واحدة من Supabase SQL Editor قبل نشر ملفات التطبيق الجديدة.

begin;

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

alter table public.users
  add column if not exists instagram_company_id text;

-- توسيع قيد الدور الحالي (إن وجد) من دون تعديل بيانات المستخدمين.
do $$
declare
  constraint_row record;
  has_viewer_constraint boolean := false;
begin
  for constraint_row in
    select conname, pg_get_constraintdef(oid) as definition
    from pg_constraint
    where conrelid = 'public.users'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%role%'
  loop
    if constraint_row.definition ilike '%instagram_viewer%' then
      has_viewer_constraint := true;
    elsif constraint_row.definition ilike '%admin%'
      and constraint_row.definition ilike '%driver%'
      and constraint_row.definition ilike '%company%' then
      execute format('alter table public.users drop constraint %I', constraint_row.conname);
    end if;
  end loop;

  if not has_viewer_constraint and not exists (
    select 1 from pg_constraint
    where conrelid = 'public.users'::regclass
      and conname = 'users_role_wolforder_check'
  ) then
    alter table public.users
      add constraint users_role_wolforder_check
      check (role in ('admin', 'driver', 'company', 'instagram_viewer')) not valid;
    alter table public.users validate constraint users_role_wolforder_check;
  end if;
end
$$;

create table if not exists public.instagram_company_links (
  id uuid primary key default gen_random_uuid(),
  company_id text not null unique,
  public_slug text not null unique default lower(encode(gen_random_bytes(18), 'hex')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint instagram_company_links_slug_check check (public_slug ~ '^[a-z0-9-]{20,100}$')
);

create table if not exists public.instagram_products (
  id uuid primary key default gen_random_uuid(),
  company_id text not null,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint instagram_products_name_check check (char_length(btrim(name)) between 2 and 120)
);

create table if not exists public.instagram_inventory (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.instagram_products(id) on delete restrict,
  color text not null,
  size text not null,
  initial_quantity integer not null default 0,
  available_quantity integer not null default 0,
  reserved_quantity integer not null default 0,
  sold_quantity integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint instagram_inventory_color_check check (char_length(btrim(color)) between 1 and 60),
  constraint instagram_inventory_size_check check (char_length(btrim(size)) between 1 and 60),
  constraint instagram_inventory_quantities_check check (
    initial_quantity >= 0 and available_quantity >= 0 and reserved_quantity >= 0 and sold_quantity >= 0
  )
);

create table if not exists public.instagram_shipping_batches (
  id uuid primary key default gen_random_uuid(),
  batch_number bigint generated by default as identity unique,
  partner_name text not null,
  note text not null default '',
  order_count integer not null default 0,
  piece_count integer not null default 0,
  created_by text,
  created_at timestamptz not null default now(),
  constraint instagram_shipping_batches_partner_check check (char_length(btrim(partner_name)) between 2 and 120),
  constraint instagram_shipping_batches_counts_check check (order_count > 0 and piece_count > 0)
);

create table if not exists public.instagram_orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  order_number_text text generated always as (order_number::text) stored,
  company_id text not null,
  company_name text not null default '',
  customer_name text not null,
  customer_phone text not null,
  address text not null,
  order_type text not null,
  status text not null default 'قيد المتابعة',
  note text not null default '',
  driver_id text,
  driver_name text not null default '',
  idempotency_key uuid not null unique,
  request_fingerprint text not null,
  request_ip_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status_changed_at timestamptz not null default now(),
  constraint instagram_orders_type_check check (order_type in ('توصيل', 'شحن')),
  constraint instagram_orders_status_check check (status in ('قيد المتابعة', 'تم', 'مؤجل', 'ملغي', 'مرتجع')),
  constraint instagram_orders_name_check check (char_length(btrim(customer_name)) between 2 and 100),
  constraint instagram_orders_phone_check check (customer_phone ~ '^\+?[0-9]{8,15}$'),
  constraint instagram_orders_address_check check (char_length(btrim(address)) between 5 and 300)
);

alter table public.instagram_orders
  add column if not exists shipping_batch_id uuid references public.instagram_shipping_batches(id) on delete restrict;
alter table public.instagram_orders add column if not exists shipping_partner text not null default '';
alter table public.instagram_orders add column if not exists shipping_handed_at timestamptz;

create table if not exists public.instagram_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.instagram_orders(id) on delete cascade,
  product_id uuid not null references public.instagram_products(id) on delete restrict,
  inventory_id uuid not null references public.instagram_inventory(id) on delete restrict,
  product_name text not null,
  color text not null,
  size text not null,
  quantity integer not null,
  created_at timestamptz not null default now(),
  constraint instagram_order_items_quantity_check check (quantity between 1 and 100),
  constraint instagram_order_items_variant_unique unique (order_id, inventory_id)
);

create table if not exists public.instagram_inventory_movements (
  id bigint generated by default as identity primary key,
  inventory_id uuid not null references public.instagram_inventory(id) on delete restrict,
  order_id uuid references public.instagram_orders(id) on delete restrict,
  movement_type text not null,
  available_delta integer not null default 0,
  reserved_delta integer not null default 0,
  sold_delta integer not null default 0,
  reason text not null default '',
  actor_id text,
  event_key uuid not null default gen_random_uuid() unique,
  created_at timestamptz not null default now()
);

create table if not exists public.instagram_order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.instagram_orders(id) on delete restrict,
  old_status text,
  new_status text not null,
  actor_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.instagram_public_rate_limits (
  bucket_key text primary key,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 0,
  updated_at timestamptz not null default now()
);

create unique index if not exists instagram_products_company_name_uq
  on public.instagram_products (company_id, lower(name));
create unique index if not exists instagram_inventory_variant_uq
  on public.instagram_inventory (product_id, lower(color), lower(size));

create or replace function public.wolforder_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists instagram_company_links_touch on public.instagram_company_links;
create trigger instagram_company_links_touch before update on public.instagram_company_links
for each row execute function public.wolforder_touch_updated_at();
drop trigger if exists instagram_products_touch on public.instagram_products;
create trigger instagram_products_touch before update on public.instagram_products
for each row execute function public.wolforder_touch_updated_at();
drop trigger if exists instagram_inventory_touch on public.instagram_inventory;
create trigger instagram_inventory_touch before update on public.instagram_inventory
for each row execute function public.wolforder_touch_updated_at();

create or replace function public.validate_instagram_viewer_company()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.role = 'instagram_viewer' then
    if new.instagram_company_id is null or not exists (
      select 1 from public.users company
      where company.id::text = new.instagram_company_id
        and company.role = 'company'
    ) then
      raise exception 'INVALID_INSTAGRAM_VIEWER_COMPANY' using errcode = 'P0001';
    end if;
  elsif new.instagram_company_id is not null then
    new.instagram_company_id := null;
  end if;
  return new;
end;
$$;

drop trigger if exists users_validate_instagram_viewer on public.users;
create trigger users_validate_instagram_viewer
before insert or update of role, instagram_company_id on public.users
for each row execute function public.validate_instagram_viewer_company();

create or replace function public.create_instagram_product(
  p_company_id text,
  p_name text,
  p_is_active boolean,
  p_variants jsonb,
  p_actor_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  new_product public.instagram_products%rowtype;
  new_inventory public.instagram_inventory%rowtype;
  variant jsonb;
  variant_count integer;
  quantity_value integer;
begin
  if not exists (select 1 from public.users where id::text = p_company_id and role = 'company') then
    raise exception 'INVALID_COMPANY' using errcode = 'P0001';
  end if;
  if char_length(btrim(coalesce(p_name, ''))) not between 2 and 120 then
    raise exception 'INVALID_PRODUCT' using errcode = 'P0001';
  end if;
  if p_variants is null or jsonb_typeof(p_variants) <> 'array' then
    raise exception 'INVALID_VARIANTS' using errcode = 'P0001';
  end if;
  variant_count := jsonb_array_length(p_variants);
  if variant_count < 1 or variant_count > 200 then
    raise exception 'INVALID_VARIANTS' using errcode = 'P0001';
  end if;

  insert into public.instagram_products (company_id, name, is_active)
  values (p_company_id, btrim(p_name), coalesce(p_is_active, true))
  returning * into new_product;

  for variant in select value from jsonb_array_elements(p_variants)
  loop
    quantity_value := (variant->>'quantity')::integer;
    if char_length(btrim(coalesce(variant->>'color', ''))) < 1
      or char_length(btrim(coalesce(variant->>'size', ''))) < 1
      or quantity_value < 0 then
      raise exception 'INVALID_VARIANT' using errcode = 'P0001';
    end if;

    insert into public.instagram_inventory (
      product_id, color, size, initial_quantity, available_quantity, reserved_quantity, sold_quantity
    ) values (
      new_product.id, btrim(variant->>'color'), btrim(variant->>'size'),
      quantity_value, quantity_value, 0, 0
    ) returning * into new_inventory;

    insert into public.instagram_inventory_movements (
      inventory_id, movement_type, available_delta, reason, actor_id
    ) values (
      new_inventory.id, 'initial_stock', quantity_value, 'إنشاء المخزون الأساسي', p_actor_id
    );
  end loop;

  return to_jsonb(new_product);
end;
$$;

create or replace function public.add_instagram_variant(
  p_product_id uuid,
  p_color text,
  p_size text,
  p_quantity integer,
  p_actor_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  new_inventory public.instagram_inventory%rowtype;
begin
  if p_quantity < 0 or char_length(btrim(coalesce(p_color, ''))) < 1 or char_length(btrim(coalesce(p_size, ''))) < 1 then
    raise exception 'INVALID_VARIANT' using errcode = 'P0001';
  end if;
  if not exists (select 1 from public.instagram_products where id = p_product_id) then
    raise exception 'INVALID_PRODUCT' using errcode = 'P0001';
  end if;

  insert into public.instagram_inventory (
    product_id, color, size, initial_quantity, available_quantity, reserved_quantity, sold_quantity
  ) values (
    p_product_id, btrim(p_color), btrim(p_size), p_quantity, p_quantity, 0, 0
  ) returning * into new_inventory;

  insert into public.instagram_inventory_movements (
    inventory_id, movement_type, available_delta, reason, actor_id
  ) values (new_inventory.id, 'initial_stock', p_quantity, 'إضافة لون ومقاس جديد', p_actor_id);

  return to_jsonb(new_inventory);
end;
$$;

create or replace function public.adjust_instagram_inventory(
  p_inventory_id uuid,
  p_delta integer,
  p_reason text,
  p_actor_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  inventory_row public.instagram_inventory%rowtype;
begin
  if p_delta = 0 or char_length(btrim(coalesce(p_reason, ''))) < 3 then
    raise exception 'INVALID_ADJUSTMENT' using errcode = 'P0001';
  end if;
  select * into inventory_row from public.instagram_inventory where id = p_inventory_id for update;
  if not found then raise exception 'INVALID_INVENTORY' using errcode = 'P0001'; end if;
  if inventory_row.available_quantity + p_delta < 0 or inventory_row.initial_quantity + p_delta < 0 then
    raise exception 'INSUFFICIENT_AVAILABLE_STOCK' using errcode = 'P0001';
  end if;

  update public.instagram_inventory
  set initial_quantity = initial_quantity + p_delta,
      available_quantity = available_quantity + p_delta
  where id = p_inventory_id
  returning * into inventory_row;

  insert into public.instagram_inventory_movements (
    inventory_id, movement_type, available_delta, reason, actor_id
  ) values (
    p_inventory_id,
    case when p_delta > 0 then 'adjustment_in' else 'adjustment_out' end,
    p_delta, btrim(p_reason), p_actor_id
  );
  return to_jsonb(inventory_row);
end;
$$;

create or replace function public.create_instagram_order(
  p_public_slug text,
  p_customer_name text,
  p_customer_phone text,
  p_address text,
  p_order_type text,
  p_note text,
  p_items jsonb,
  p_idempotency_key uuid,
  p_request_fingerprint text,
  p_rate_bucket text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  company_value text;
  company_name_value text;
  order_row public.instagram_orders%rowtype;
  existing_order public.instagram_orders%rowtype;
  inventory_row record;
  item jsonb;
  item_quantity integer;
  item_inventory_id uuid;
  rate_count integer;
begin
  insert into public.instagram_public_rate_limits (bucket_key, window_started_at, request_count, updated_at)
  values (p_rate_bucket, now(), 1, now())
  on conflict (bucket_key) do update
  set request_count = case
        when instagram_public_rate_limits.window_started_at < now() - interval '10 minutes' then 1
        else instagram_public_rate_limits.request_count + 1
      end,
      window_started_at = case
        when instagram_public_rate_limits.window_started_at < now() - interval '10 minutes' then now()
        else instagram_public_rate_limits.window_started_at
      end,
      updated_at = now()
  returning request_count into rate_count;
  if rate_count > 30 then raise exception 'RATE_LIMITED' using errcode = 'P0001'; end if;

  select company_id into company_value
  from public.instagram_company_links
  where public_slug = p_public_slug and is_active = true;
  if company_value is null then raise exception 'INVALID_PUBLIC_LINK' using errcode = 'P0001'; end if;

  select name into company_name_value from public.users
  where id::text = company_value and role = 'company';
  if company_name_value is null then raise exception 'INVALID_COMPANY' using errcode = 'P0001'; end if;

  if p_order_type not in ('توصيل', 'شحن')
    or p_items is null
    or jsonb_typeof(p_items) <> 'array'
    or coalesce(jsonb_array_length(p_items), 0) not between 1 and 20 then
    raise exception 'INVALID_ORDER' using errcode = 'P0001';
  end if;

  select * into existing_order from public.instagram_orders where idempotency_key = p_idempotency_key;
  if found then
    return jsonb_build_object('id', existing_order.id, 'order_number', existing_order.order_number, 'duplicate', true);
  end if;

  perform pg_advisory_xact_lock(hashtextextended(company_value || ':' || p_request_fingerprint, 0));
  select * into existing_order
  from public.instagram_orders
  where company_id = company_value
    and request_fingerprint = p_request_fingerprint
    and created_at >= now() - interval '2 minutes'
  order by created_at desc
  limit 1;
  if found then
    return jsonb_build_object('id', existing_order.id, 'order_number', existing_order.order_number, 'duplicate', true);
  end if;

  insert into public.instagram_orders (
    company_id, company_name, customer_name, customer_phone, address, order_type,
    status, note, idempotency_key, request_fingerprint, request_ip_hash
  ) values (
    company_value, company_name_value, btrim(p_customer_name), p_customer_phone, btrim(p_address),
    p_order_type, 'قيد المتابعة', btrim(coalesce(p_note, '')), p_idempotency_key,
    p_request_fingerprint, p_rate_bucket
  ) returning * into order_row;

  -- ترتيب الأقفال يمنع deadlocks إذا وصلت طلبات متزامنة بترتيب أصناف مختلف.
  for item in
    select value from jsonb_array_elements(p_items)
    order by value->>'inventory_id'
  loop
    item_inventory_id := (item->>'inventory_id')::uuid;
    item_quantity := (item->>'quantity')::integer;
    if item_quantity not between 1 and 100 then raise exception 'INVALID_QUANTITY' using errcode = 'P0001'; end if;

    select i.id, i.product_id, i.color, i.size, i.available_quantity,
           p.name as product_name
    into inventory_row
    from public.instagram_inventory i
    join public.instagram_products p on p.id = i.product_id
    where i.id = item_inventory_id
      and i.is_active = true
      and p.is_active = true
      and p.company_id = company_value
    for update of i;

    if not found then raise exception 'INVALID_INVENTORY' using errcode = 'P0001'; end if;
    if inventory_row.available_quantity < item_quantity then
      raise exception 'OUT_OF_STOCK:%:%:%', inventory_row.product_name, inventory_row.color, inventory_row.size using errcode = 'P0001';
    end if;

    update public.instagram_inventory
    set available_quantity = available_quantity - item_quantity,
        reserved_quantity = reserved_quantity + item_quantity
    where id = item_inventory_id;

    insert into public.instagram_order_items (
      order_id, product_id, inventory_id, product_name, color, size, quantity
    ) values (
      order_row.id, inventory_row.product_id, item_inventory_id, inventory_row.product_name,
      inventory_row.color, inventory_row.size, item_quantity
    );

    insert into public.instagram_inventory_movements (
      inventory_id, order_id, movement_type, available_delta, reserved_delta, reason
    ) values (
      item_inventory_id, order_row.id, 'reservation', -item_quantity, item_quantity, 'حجز طلب إنستغرام'
    );
  end loop;

  insert into public.instagram_order_status_history (order_id, old_status, new_status)
  values (order_row.id, null, 'قيد المتابعة');

  return jsonb_build_object('id', order_row.id, 'order_number', order_row.order_number, 'duplicate', false);
end;
$$;

create or replace function public.update_instagram_order_state(
  p_order_id uuid,
  p_new_status text,
  p_actor_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  order_row public.instagram_orders%rowtype;
  item_row record;
  previous_status text;
  old_bucket text;
  new_bucket text;
  available_change integer;
  reserved_change integer;
  sold_change integer;
begin
  if p_new_status not in ('قيد المتابعة', 'تم', 'مؤجل', 'ملغي', 'مرتجع') then
    raise exception 'INVALID_STATUS' using errcode = 'P0001';
  end if;
  select * into order_row from public.instagram_orders where id = p_order_id for update;
  if not found then raise exception 'INVALID_ORDER' using errcode = 'P0001'; end if;
  if order_row.status = p_new_status then return to_jsonb(order_row); end if;
  previous_status := order_row.status;

  old_bucket := case when previous_status in ('قيد المتابعة', 'مؤجل') then 'reserved' when previous_status = 'تم' then 'sold' else 'released' end;
  new_bucket := case when p_new_status in ('قيد المتابعة', 'مؤجل') then 'reserved' when p_new_status = 'تم' then 'sold' else 'released' end;

  if old_bucket <> new_bucket then
    for item_row in select inventory_id, quantity from public.instagram_order_items where order_id = p_order_id order by inventory_id
    loop
      perform 1 from public.instagram_inventory where id = item_row.inventory_id for update;
      available_change := 0; reserved_change := 0; sold_change := 0;
      if old_bucket = 'reserved' and new_bucket = 'sold' then reserved_change := -item_row.quantity; sold_change := item_row.quantity;
      elsif old_bucket = 'reserved' and new_bucket = 'released' then reserved_change := -item_row.quantity; available_change := item_row.quantity;
      elsif old_bucket = 'sold' and new_bucket = 'released' then sold_change := -item_row.quantity; available_change := item_row.quantity;
      elsif old_bucket = 'sold' and new_bucket = 'reserved' then sold_change := -item_row.quantity; reserved_change := item_row.quantity;
      elsif old_bucket = 'released' and new_bucket = 'reserved' then available_change := -item_row.quantity; reserved_change := item_row.quantity;
      elsif old_bucket = 'released' and new_bucket = 'sold' then available_change := -item_row.quantity; sold_change := item_row.quantity;
      end if;

      update public.instagram_inventory
      set available_quantity = available_quantity + available_change,
          reserved_quantity = reserved_quantity + reserved_change,
          sold_quantity = sold_quantity + sold_change
      where id = item_row.inventory_id
        and available_quantity + available_change >= 0
        and reserved_quantity + reserved_change >= 0
        and sold_quantity + sold_change >= 0;
      if not found then raise exception 'OUT_OF_STOCK' using errcode = 'P0001'; end if;

      insert into public.instagram_inventory_movements (
        inventory_id, order_id, movement_type, available_delta, reserved_delta, sold_delta, reason, actor_id
      ) values (
        item_row.inventory_id, p_order_id,
        case when new_bucket = 'released' and p_new_status = 'مرتجع' then 'return_release'
             when new_bucket = 'released' then 'cancellation_release'
             when new_bucket = 'sold' then 'sale'
             when old_bucket = 'released' then 'reopen_reservation'
             else 'status_rebalance' end,
        available_change, reserved_change, sold_change, previous_status || ' ← ' || p_new_status, p_actor_id
      );
    end loop;
  end if;

  update public.instagram_orders
  set status = p_new_status, status_changed_at = now(), updated_at = now()
  where id = p_order_id returning * into order_row;
  insert into public.instagram_order_status_history (order_id, old_status, new_status, actor_id)
  values (p_order_id, previous_status, p_new_status, p_actor_id);
  return to_jsonb(order_row);
end;
$$;

create or replace function public.assign_instagram_order_driver(
  p_order_id uuid,
  p_driver_id text,
  p_driver_name text,
  p_actor_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare order_row public.instagram_orders%rowtype;
begin
  update public.instagram_orders
  set driver_id = p_driver_id, driver_name = btrim(p_driver_name), updated_at = now()
  where id = p_order_id and order_type = 'توصيل'
  returning * into order_row;
  if not found then raise exception 'INVALID_DELIVERY_ORDER' using errcode = 'P0001'; end if;
  insert into public.instagram_order_status_history (order_id, old_status, new_status, actor_id)
  values (p_order_id, order_row.status, order_row.status, p_actor_id);
  return to_jsonb(order_row);
end;
$$;

create or replace function public.create_instagram_shipping_batch(
  p_order_ids uuid[],
  p_partner_name text,
  p_note text,
  p_actor_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  batch_row public.instagram_shipping_batches%rowtype;
  selected_order_count integer;
  selected_piece_count integer;
begin
  if coalesce(cardinality(p_order_ids), 0) not between 1 and 500
    or char_length(btrim(coalesce(p_partner_name, ''))) not between 2 and 120 then
    raise exception 'INVALID_SHIPPING_BATCH' using errcode = 'P0001';
  end if;

  -- قفل الطلبات بترتيب ثابت ومنع إدخال طلب توصيل أو طلب سبق تسليمه ضمن دفعة أخرى.
  perform 1 from public.instagram_orders
  where id = any(p_order_ids)
  order by id
  for update;

  select count(*), coalesce(sum(item_totals.pieces), 0)::integer
  into selected_order_count, selected_piece_count
  from public.instagram_orders orders
  join lateral (
    select coalesce(sum(quantity), 0)::integer as pieces
    from public.instagram_order_items
    where order_id = orders.id
  ) item_totals on true
  where orders.id = any(p_order_ids)
    and orders.order_type = 'شحن'
    and orders.status in ('قيد المتابعة', 'مؤجل')
    and orders.shipping_batch_id is null;

  if selected_order_count <> cardinality(p_order_ids) or selected_piece_count < 1 then
    raise exception 'INVALID_OR_ALREADY_BATCHED_SHIPPING_ORDER' using errcode = 'P0001';
  end if;

  insert into public.instagram_shipping_batches (
    partner_name, note, order_count, piece_count, created_by
  ) values (
    btrim(p_partner_name), btrim(coalesce(p_note, '')), selected_order_count, selected_piece_count, p_actor_id
  ) returning * into batch_row;

  update public.instagram_orders
  set shipping_batch_id = batch_row.id,
      shipping_partner = batch_row.partner_name,
      shipping_handed_at = now(),
      updated_at = now()
  where id = any(p_order_ids);

  return to_jsonb(batch_row);
end;
$$;

create or replace view public.instagram_inventory_stats
with (security_invoker = true)
as
select
  i.id as inventory_id,
  p.id as product_id,
  p.company_id,
  coalesce(company.name, '') as company_name,
  p.name as product_name,
  p.is_active as product_active,
  i.is_active as inventory_active,
  i.color,
  i.size,
  i.initial_quantity,
  coalesce(sum(oi.quantity) filter (where o.status = 'تم'), 0)::bigint as sold_quantity,
  coalesce(sum(oi.quantity) filter (where o.status = 'قيد المتابعة'), 0)::bigint as reserved_quantity,
  coalesce(sum(oi.quantity) filter (where o.status = 'مؤجل'), 0)::bigint as postponed_quantity,
  coalesce(sum(oi.quantity) filter (where o.status = 'ملغي'), 0)::bigint as cancelled_quantity,
  coalesce(sum(oi.quantity) filter (where o.status = 'مرتجع'), 0)::bigint as returned_quantity,
  i.available_quantity as remaining_quantity
from public.instagram_inventory i
join public.instagram_products p on p.id = i.product_id
left join public.users company on company.id::text = p.company_id and company.role = 'company'
left join public.instagram_order_items oi on oi.inventory_id = i.id
left join public.instagram_orders o on o.id = oi.order_id
group by i.id, p.id, p.company_id, company.name, p.name, p.is_active, i.is_active,
         i.color, i.size, i.initial_quantity, i.available_quantity;

create or replace view public.instagram_export_rows
with (security_invoker = true)
as
select
  o.id as order_id,
  o.order_number,
  o.created_at,
  o.company_id,
  o.company_name,
  o.customer_name,
  o.customer_phone,
  o.address,
  o.order_type,
  o.status,
  o.note,
  oi.product_id,
  oi.inventory_id,
  oi.product_name,
  oi.color,
  oi.size,
  oi.quantity
from public.instagram_orders o
join public.instagram_order_items oi on oi.order_id = o.id;

-- لا تمنح المتصفح وصولاً مباشراً إلى بيانات إنستغرام؛ الوصول حصراً عبر الخادم Service Role.
alter table public.instagram_company_links enable row level security;
alter table public.instagram_products enable row level security;
alter table public.instagram_inventory enable row level security;
alter table public.instagram_shipping_batches enable row level security;
alter table public.instagram_orders enable row level security;
alter table public.instagram_order_items enable row level security;
alter table public.instagram_inventory_movements enable row level security;
alter table public.instagram_order_status_history enable row level security;
alter table public.instagram_public_rate_limits enable row level security;

revoke all on public.instagram_company_links, public.instagram_products, public.instagram_inventory,
  public.instagram_shipping_batches, public.instagram_orders, public.instagram_order_items, public.instagram_inventory_movements,
  public.instagram_order_status_history, public.instagram_public_rate_limits from public, anon, authenticated;
grant all on public.instagram_company_links, public.instagram_products, public.instagram_inventory,
  public.instagram_shipping_batches, public.instagram_orders, public.instagram_order_items, public.instagram_inventory_movements,
  public.instagram_order_status_history, public.instagram_public_rate_limits to service_role;
revoke all on public.instagram_inventory_stats, public.instagram_export_rows from public, anon, authenticated;
grant select on public.instagram_inventory_stats, public.instagram_export_rows to service_role;

revoke execute on function public.create_instagram_product(text, text, boolean, jsonb, text) from public, anon, authenticated;
revoke execute on function public.add_instagram_variant(uuid, text, text, integer, text) from public, anon, authenticated;
revoke execute on function public.adjust_instagram_inventory(uuid, integer, text, text) from public, anon, authenticated;
revoke execute on function public.create_instagram_order(text, text, text, text, text, text, jsonb, uuid, text, text) from public, anon, authenticated;
revoke execute on function public.update_instagram_order_state(uuid, text, text) from public, anon, authenticated;
revoke execute on function public.assign_instagram_order_driver(uuid, text, text, text) from public, anon, authenticated;
revoke execute on function public.create_instagram_shipping_batch(uuid[], text, text, text) from public, anon, authenticated;
revoke execute on function public.wolforder_touch_updated_at() from public, anon, authenticated;
revoke execute on function public.validate_instagram_viewer_company() from public, anon, authenticated;
grant execute on function public.create_instagram_product(text, text, boolean, jsonb, text) to service_role;
grant execute on function public.add_instagram_variant(uuid, text, text, integer, text) to service_role;
grant execute on function public.adjust_instagram_inventory(uuid, integer, text, text) to service_role;
grant execute on function public.create_instagram_order(text, text, text, text, text, text, jsonb, uuid, text, text) to service_role;
grant execute on function public.update_instagram_order_state(uuid, text, text) to service_role;
grant execute on function public.assign_instagram_order_driver(uuid, text, text, text) to service_role;
grant execute on function public.create_instagram_shipping_batch(uuid[], text, text, text) to service_role;

commit;

-- فهارس الطلبات الحالية: خارج transaction لتقليل حجب الكتابة على الجدول الكبير.
create index concurrently if not exists orders_company_created_idx on public.orders (company_id, created_at desc);
create index concurrently if not exists orders_driver_created_idx on public.orders (driver_id, created_at desc);
create index concurrently if not exists orders_status_created_idx on public.orders (status, created_at desc);
create index concurrently if not exists orders_company_status_created_idx on public.orders (company_id, status, created_at desc);
create index concurrently if not exists orders_driver_status_created_idx on public.orders (driver_id, status, created_at desc);
create index concurrently if not exists orders_company_order_type_idx on public.orders (company_id, order_type);

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'orders' and column_name = 'order_number'
      and data_type in ('text', 'character varying', 'character')
  ) then
    execute 'create index if not exists orders_order_number_trgm_idx on public.orders using gin (order_number gin_trgm_ops)';
  end if;
end
$$;
create index concurrently if not exists orders_customer_name_trgm_idx on public.orders using gin (customer_name gin_trgm_ops);
create index concurrently if not exists orders_customer_number_trgm_idx on public.orders using gin (customer_number gin_trgm_ops);
create index concurrently if not exists orders_address_trgm_idx on public.orders using gin (address gin_trgm_ops);
create index concurrently if not exists orders_contents_trgm_idx on public.orders using gin (order_contents gin_trgm_ops);
create index concurrently if not exists orders_note_trgm_idx on public.orders using gin (note gin_trgm_ops);
create index concurrently if not exists orders_company_name_trgm_idx on public.orders using gin (company_name gin_trgm_ops);
create index concurrently if not exists orders_driver_name_trgm_idx on public.orders using gin (driver_name gin_trgm_ops);

create index concurrently if not exists instagram_orders_company_created_idx on public.instagram_orders (company_id, created_at desc);
create index concurrently if not exists instagram_orders_company_status_created_idx on public.instagram_orders (company_id, status, created_at desc);
create index concurrently if not exists instagram_orders_type_created_idx on public.instagram_orders (order_type, created_at desc);
create index concurrently if not exists instagram_orders_driver_created_idx on public.instagram_orders (driver_id, created_at desc);
create index concurrently if not exists instagram_orders_shipping_batch_idx on public.instagram_orders (shipping_batch_id, created_at desc);
create index concurrently if not exists instagram_orders_fingerprint_created_idx on public.instagram_orders (company_id, request_fingerprint, created_at desc);
create index concurrently if not exists instagram_orders_number_trgm_idx on public.instagram_orders using gin (order_number_text gin_trgm_ops);
create index concurrently if not exists instagram_orders_customer_name_trgm_idx on public.instagram_orders using gin (customer_name gin_trgm_ops);
create index concurrently if not exists instagram_orders_phone_trgm_idx on public.instagram_orders using gin (customer_phone gin_trgm_ops);
create index concurrently if not exists instagram_orders_address_trgm_idx on public.instagram_orders using gin (address gin_trgm_ops);
create index concurrently if not exists instagram_orders_company_name_trgm_idx on public.instagram_orders using gin (company_name gin_trgm_ops);
create index concurrently if not exists instagram_orders_note_trgm_idx on public.instagram_orders using gin (note gin_trgm_ops);
create index concurrently if not exists instagram_items_order_idx on public.instagram_order_items (order_id);
create index concurrently if not exists instagram_items_inventory_order_idx on public.instagram_order_items (inventory_id, order_id);
create index concurrently if not exists instagram_items_product_order_idx on public.instagram_order_items (product_id, order_id);
create index concurrently if not exists instagram_movements_inventory_created_idx on public.instagram_inventory_movements (inventory_id, created_at desc);
create index concurrently if not exists instagram_movements_order_idx on public.instagram_inventory_movements (order_id);

analyze public.orders;
analyze public.instagram_orders;
analyze public.instagram_order_items;
analyze public.instagram_inventory;
